env:
  browser: true
  es2021: true
  node: true
extends:
  - eslint:recommended
  - plugin:react/recommended
  - plugin:react-hooks/recommended
  - plugin:@next/next/recommended
overrides: []
parserOptions:
  ecmaVersion: latest
  sourceType: module
plugins:
  - react
rules:
  indent:
    - error
    - 2
  linebreak-style:
    - warn
    - windows
  quotes:
    - error
    - double
  semi:
    - error
    - always
  no-unused-vars:
    - warn
    - vars: all
      args: none
  no-console:
    - warn
    - allow: ["warn", "error"]
  space-before-function-paren:
    - error
    - never
  array-bracket-spacing:
    - error
    - always
    - objectsInArrays: false
  object-curly-spacing:
    - error
    - always
  no-multiple-empty-lines:
    - error
    - max: 1
      maxEOF: 1
      maxBOF: 0
  no-trailing-spaces:
    - error
    - skipBlankLines: true
  no-multi-spaces:
    - error
  require-await: error

  react/prop-types: off
  react/react-in-jsx-scope: off
